import Head from 'next/head'
import Image from 'next/image'
import Search from '../components/Search'
import Weather from "../components/Weather"
import React, {useState} from 'react'
import axios from "axios";
import { BsSearch } from 'react-icons/bs';
import Loading from '../components/Loading'

export default function Home() {
  const API_KEY = "1b8515dd96a933b5bd445607e98dfcb0";

  const [weather,setWeather] = useState({});
  const [city, setCity] = useState("");
  const [loading, setLoading] = useState(false);


  const url = 'https://api.openweathermap.org/data/2.5/weather?q='+city+'&units=imperial&appid='+process.env.NEXT_PUBLIC_API_KEY;



  const getWeather = async (event, city) => {
    event.preventDefault();

    setLoading(true);
    
    await axios.get(url).then((response) => {
      setWeather(response.data);
      
      console.log(weather);
    });


    setCity("");
    
    setLoading(false);
  }

  if (loading){
    return <Loading />
  } else {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
          src="https://images.unsplash.com/photo-1505487460685-7e53b8ee2300?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
          layout='fill'
          className='object-cover -z-10'
        />

      {/* Search Bar */}
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 mb-10 text-gray-300 z-10'>
          <form onSubmit={getWeather} className='flex justify-between items-center w-full m-auto p-3 bg-black opacity-70 border border-gray-300 text-white rounded-2xl'>
            <div>
              <input
                className='bg-black opacity-70 border-none text-white focus:outline-none text-2xl'
                type='text'
                placeholder='Search city'
                onChange={(e) => setCity(e.target.value)}
                value={city}
              />
            </div>
            <button onClick = {getWeather} >
              <BsSearch size={20} />
            </button>
          </form>
      </div>

      {weather.main && <Weather data={weather}/>}

     
      
    </div>
  )};
}
